manifests/init.pp
templates/ipset.service.epp

improve datatypes / rename internal variables

---

.sync.yml
.travis.yml
data/RedHat-6.yaml
hiera.yaml
manifests/init.pp
metadata.json
spec/classes/init_spec.rb
spec/defines/init_spec.rb
templates/init.redhat.epp
templates/init.upstart.erb

enable CentOS 6 support

---

README.md
REFERENCE.md
manifests/set.pp
types/options.pp
types/set/array.pp
types/set/file_url.pp
types/set/puppet_url.pp
types/settype.pp
types/type.pp

update puppet-strings/README.md documentation

---

.sync.yml
.travis.yml
Gemfile
Rakefile
spec/spec_helper.rb

modulesync 2.9.0

---

metadata.json

Add VirtuozzoLinux support

---

CHANGELOG.md
metadata.json

release v1.2.0

---

templates/init.redhat.epp

CentOS 6: use correct sys v syntax

---

CHANGELOG.md
metadata.json

release 1.2.1

---

CHANGELOG.md
metadata.json

release v1.2.3

---

README.md

Update documentation to add  an example for `ipset::unmanaged`.
Fixes: #23

Add unmanaged ipset example to README.md

---

.github/SECURITY.md
.msync.yml
.rubocop.yml
.travis.yml
Gemfile
manifests/init.pp
manifests/set.pp
manifests/unmanaged.pp
spec/spec_helper_acceptance.rb

modulesync 3.0.0 & puppet-lint updates

---

.github/workflows/ci.yml
Gemfile

modulesync 4.2.0

---

.msync.yml
Gemfile
spec/acceptance/ipset_spec.rb
spec/classes/init_spec.rb
spec/defines/init_spec.rb
spec/spec_helper.rb
spec/spec_helper_acceptance.rb

modulesync 5.0.0

---

CHANGELOG.md
README.md
REFERENCE.md
metadata.json

Release 2.1.0

---

.github/CONTRIBUTING.md
.github/workflows/ci.yml
.github/workflows/release.yml
.msync.yml
Dockerfile
Gemfile
Rakefile
manifests/init.pp
spec/spec_helper.rb

modulesync 5.3.0

---

metadata.json

puppet/systemd: Allow 5.x & 6.x

---

metadata.json

Drop OracleLinux 7, Add EL9/Alma/Rocky support

---

manifests/set.pp

Replace merge() with native Puppet code

---

.github/CONTRIBUTING.md
.github/labeler.yml
.github/release.yml
.github/workflows/ci.yml
.github/workflows/labeler.yml
.github/workflows/release.yml
.msync.yml
.pmtignore
Gemfile
spec/spec_helper.rb

modulesync 9.3.0

---

metadata.json

drop support for CentOS 8 -- EOL

---

metadata.json

drop support for Debian 10 -- EOL

---

metadata.json

drop support for Ubuntu 18.04 -- EOL
